
[compatibility]
	#If you use a custom "in_progress_texture" in a Power Loom recipe, the textures need to be added to this list.
	#Note that the custom textures cannot be located in a datapack because datapacks are loaded after all the textures are stitched.
	#Instead, the textures need to be located in a resourcepack.
	#Example: additionalPowerLoomClothTextures = ["domain:texture_location1", "domain:texture_location2"]
	additionalPowerLoomClothTextures = []
	#If you use a custom "pirn" in a Power Loom recipe (the second item in input list), the registry name of the pirn item and the textures need to be added to this list.
	#Note that the custom textures cannot be located in a datapack because datapacks are loaded after all the textures are stitched.
	#Instead, the textures need to be located in a resourcepack.
	#Example: additionalPowerLoomPirnTextures = [["domain:registry_name1", "domain:texture_location1"], ["domain:registry_name2", "domain:texture_location2"]]
	additionalPowerLoomPirnTextures = []
	#If you use custom inputs and outputs in a Fleshing Machine recipe, the registry name of the items and the textures need to be added to this list.
	#Note that the custom textures cannot be located in a datapack because datapacks are loaded after all the textures are stitched.
	#Instead, the textures need to be located in a resourcepack.
	#Example: additionalFleshingMachineTextures = [["domain:registry_name1", "domain:texture_location1"], ["domain:registry_name2", "domain:texture_location2"]]
	additionalFleshingMachineTextures = []

